run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 